// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knoraurtjhxdybrmezen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtub3JhdXJ0amh4ZHlicm1lemVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwNTA0NTAsImV4cCI6MjA4NjYyNjQ1MH0.0jDifgE_ey3iUO0E0tlMlEJ2iFR3i7y4EtUtEGBSW1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});